version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: comp3123_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: comp3123_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/comp3123_assigment1
      - JWT_SECRET=yourSecretKeyHere

  frontend:
    build: ./frontend
    container_name: comp3123_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api/v1

volumes:
  mongo_data:
